# -*- coding: utf-8 -*-
"""RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-yGbgYq5HJh7-CdpMKRLFg006sdxaZCx
"""

pip install langchain_community langchainhub chromadb langchain langchain-google-genai

from google.colab import userdata
userdata.get('RAG')

from langchain_community.document_loaders import WebBaseLoader
loader = WebBaseLoader(web_paths=["https://www.geeksforgeeks.org/artificial-intelligence/"])
docs = loader.load()
print(docs)

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
splits = text_splitter.split_documents(docs)

print(splits[0])
print(splits[1])

print (len(splits))

import os
from google.colab import userdata
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from langchain_community.vectorstores import Chroma

# 1. Pull your Gemini API key from Colab Secrets
os.environ["GOOGLE_API_KEY"] = userdata.get('RAG')

# 2. Initialize the Gemini embedding model (using the NEWEST generation model)
embeddings = GoogleGenerativeAIEmbeddings(model="models/gemini-embedding-001")

# 3. Pass your text splits and the embedding model to Chroma
vectorstore = Chroma.from_documents(documents=splits, embedding=embeddings)

print("Vector embeddings created and stored successfully!")

print(vectorstore._collection.count())

print(vectorstore._collection.get())

print("\nCollection 1 - ", vectorstore._collection.get(ids=['38e6508f-7db3-4337-941d-365807cea087'], include=["embeddings", "documents"]))
print("\nCollection 2 - ", vectorstore._collection.get(ids=['06f6737d-fa3a-4e24-b7ae-1169b1d3def2'], include=["embeddings", "documents"]))
print("\nCollection 3 - ", vectorstore._collection.get(ids=['4be9fa1d-f72b-4228-9d73-451abb9cb076'], include=["embeddings", "documents"]))
print("\nCollection 4 - ", vectorstore._collection.get(ids=['f4ef773f-9c8c-426a-88a6-55c8ebae5207'], include=["embeddings", "documents"]))
print("\nCollection 5 - ", vectorstore._collection.get(ids=['fa87566c-d138-4a40-9842-aa95c0b842a'], include=["embeddings", "documents"]))

"""RAG PIPELINE"""

retriever = vectorstore.as_retriever()

"""RAG AUGUMENTATION"""

from langchain_core.prompts import PromptTemplate

template = """You are an assistant for question-answering tasks. Use the following pieces of retrieved context to answer the question. If you don't know the answer, just say that you don't know. Use three sentences maximum and keep the answer concise.

Question: {question}
Context: {context}
Answer:"""

prompt = PromptTemplate.from_template(template)

from langchain_google_genai import ChatGoogleGenerativeAI

# Use the updated Gemini 2.5 Flash model
llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash")

from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

def format_docs(docs):
    return "\n".join(doc.page_content for doc in docs)

rag_chain = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

rag_chain. invoke("brief me about Narrow AI")

rag_chain.invoke ("what do you mean by AI agents .?")